"""initial schema

Revision ID: 4b59503e9f7b
Revises: 
Create Date: 2026-02-17 14:59:07.831078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b59503e9f7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('credits_earned', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'original_url', name='uq_seller_url')
    )
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('reward_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_clicked_at'), 'clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_clicks_link_id'), 'clicks', ['link_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aws_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_seller_id'), 'rewards', ['seller_id'], unique=False)
    op.create_index(op.f('ix_rewards_status'), 'rewards', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_status'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_seller_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_clicks_link_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_clicked_at'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
